apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      containers:
      - name: calculator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 80